### ISSUE TITLE
Could not HEAD FG_2.2_patched-SNAPSHOT

### ISSUE THREAD

**Issue by Reloin** [MineDojo/MineDojo#120]
After following [Issue 113](https://github.com/MineDojo/MineDojo/issues/113) on March 14 I was able to run validate_install.py up until March 16, I was unable to build it today. MineDojo prompted error below:
`* What went wrong:
A problem occurred configuring root project 'Minecraft'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.yunfanjiang:ForgeGradle:FG_2.2_patched-SNAPSHOT.
     Required by:
         project :
      > Could not resolve com.github.yunfanjiang:ForgeGradle:FG_2.2_patched-SNAPSHOT.
         > Could not get resource 'https://www.jitpack.io/com/github/yunfanjiang/ForgeGradle/FG_2.2_patched-SNAPSHOT/ForgeGradle-FG_2.2_patched-v2.0.2-g143949b-189.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/yunfanjiang/ForgeGradle/FG_2.2_patched-SNAPSHOT/ForgeGradle-FG_2.2_patched-v2.0.2-g143949b-189.pom'.
               > Read timed out
 *Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I looked on jitpack/ForgeGradle and this is where the link points to:
![image](https://github.com/MineDojo/MineDojo/assets/17092179/0c89532f-3e1a-4200-b41a-b45def5d84ec)

Not sure is this a problem on my side or FG_2.2_patched-SNAPSHOT is currently unavailable on jitpack.

**Comment by Matoi647** [comment]
I had the same issue as you this morning, but it seems to have been automatically resolved now.

**Comment by Cu2ta1n** [comment]
Same question, it will be automatically resolved ?

**Comment by Reloin** [comment]
> Same question, it will be automatically resolved ?

Yes, to my understanding jitpack will restore the file given enough time.
