### ISSUE TITLE
tasks and guidance are often incorrect

### ISSUE THREAD

**Issue by nikhiljha** [MineDojo/MineDojo#13]
In the docs there's an example...

> Once you're in the Nether, you need to find the Ender Dragon. The easiest way to do this is by following the path of endermen. They will lead you right to the dragon.

This isn't correct. The Ender Dragon is in the End, not the Nether. The agent still needs to go to the Nether, but it needs to do that to kill Blazes, which it will use to make Eyes of Ender, which it will eventually use to find the ender dragon.

> 5. Finally, add your zombie! You can either build one using blocks, or find a ready-made one in a resource pack.

Building one with blocks is fine, but what does it mean to "find a ready-made one in a resource pack"-- that's not how resource packs work. The alternative is to carefully catch a zombie and trap it in the house.

These aren't just slightly missing information (which is fine, we can expect the agent to learn details from the datasets e.x. the way to craft eyes of ender). These tasks and guidance are just incorrect.

**Comment by nikhiljha** [comment]
Ah, noticed https://github.com/MineDojo/MineDojo/issues/2 after posting this issue. Feel free to close it as a duplicate, but from browsing through the examples it looks like _almost every single "guidance" has a glaring factual error_.

**Comment by LinxiFan** [comment]
Hi Nikhil, thank you so much for pointing out the problems. Indeed these are issues that could be very difficult to resolve unless we spend extensive human labor with Minecraft expertise. 

* For the guidance, we directly posted many outputs from GPT-3. They may not be completely correct, but we think that it's still valuable to provide the guidance even with some noise and mistakes. The guidance conditioning is optional for the model. A future improvement idea is to prompt other big LMs like BLOOM or OPT-175B and add their output to an "ensemble guidance". 
* Regarding the task in the other issue, "creative task 344 reads Build a combine harvester that collects wheat and reeds but reeds don't exist in v1.11" - reed does exist in the game as a predecessor/synonym to sugar cane. The knowledge is present in Minecraft Wiki that we scraped and open-sourced. That being said, we hope to upgrade MineDojo's Minecraft core version in the future, which will gradually accommodate a larger set of nouns and mechanisms. 

Thank you again for the careful check and thoughtful comments!

**Comment by LinxiFan** [comment]
I will close this issue for now. Would love to chat more over email if you have further questions: linxif@nvidia.com
