### ISSUE TITLE
About the factual inaccuracies in task descriptions and guidance texts

### ISSUE THREAD

**Issue by user670** [MineDojo/MineDojo#2]
I noticed that some of the "guidance" texts don't make factual sense, for example the "beat ender dragon" task says you can find the ender dragon by following the endermen from the Nether.

I wonder what are these guidance texts intended for? (For machines to read? or just for humans?) Would the factual inaccuracies cause problems, or are they considered okay in the dataset? 

**edit**: Seems like factual problems are not exclusive to guidance texts, but actual prompts too. For example, creative task 344 reads "Build a combine harvester that collects wheat and reeds" but reeds don't exist in the game (changed to sugar cane in 2011).

**edit 2**: a slightly different type of problem but I don't want to make a new issue for that, some YouTube-sourced creative tasks have malformatted task prompts like 1200 or 1203.

**Comment by yunfanjiang** [comment]
Hi, thanks for raising this issue and asking this good question. 
To answer your original question, prompts and guidance accompanied with tasks are intended to be used by models, for example a policy that can do jobs given different free-form languages specifying the goals. Ideally, a model with the entire internet-scale knowledge baked in its brain can pick up useful information from the prompt and guidance.

Regarding the problem of malformatted tasks, @Yupsong could you please take a look? Thanks
