### ISSUE TITLE
Validate install doesn't do anything

### ISSUE THREAD

**Issue by shaun-wild** [MineDojo/MineDojo#21]
```
$ python scripts/validate_install.py
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
```

This is the only output I get from running the validation script. Can anyone advise?

**Comment by TARNATlON** [comment]
Hey, It takes a bit of time until it actually gets validated.
I had to wait around 2-3 minutes before it was done :)

**Comment by shaun-wild** [comment]
I left it running for 15 minutes, there was no update in the console. 

Are you running on windows?

**Comment by Sanokei** [comment]
I am also running it on windows and it doesn't seem to be working

**Comment by yunfanjiang** [comment]
Hey @shaun-wild , thanks for opening this issue! As @Sanokei said, we only tested on Ubuntu 20.04 and MacOS (intel). It may or may not work on other platforms.
Please note that we recently released an official image [here](http://docs.minedojo.org/sections/getting_started/install.html#docker-image). We recommend you to run inside the docker image if on Windows. 
Feel free to let me know if you have any other questions!

**Comment by shaun-wild** [comment]
Does this display the actual Minecraft game? I followed the docs and it just shows a long hashed string, and the docker container never seems to start.

**Comment by yunfanjiang** [comment]
Hey @shaun-wild , if you saw the long hashed string, the docker container probably has already run in detached mode. Then you need to `docker exec -it <running_container_id> /bin/bash` to enter the docker container bash.

**Comment by shaun-wild** [comment]
`docker ps` returns no running containers for me, I'm guessing the windows support isn't there yet.

It seems the container completely fails to start.

**Comment by xieleo5** [comment]
Hi @shaun-wild , I'm also using windows and I succeed in the docker steps. After I run `docker run --gpus all -it -d -p 8080:8080 minedojo/minedojo:latest tail -f /dev/null`, I can find the running containner through `docker ps` and also in the docker desktop GUI. And I use `docker exec -it <running_container_id> /bin/bash` to connect to the containner, remember to replace <running_container_id> with the hash value you get in the first step. I also have the same log as you shown but my containner runs normally. Maybe you should try again or restart your computer?

**Comment by Sanokei** [comment]
I wasnt able to run it this way because of `nvidia-docker` (I believe)

So I used [WSL](https://docs.microsoft.com/en-us/windows/wsl/) instead and its working perfectly

**Comment by LinxiFan** [comment]
Sounds like WSL is the way to go. I'm closing this issue for now, let us know if there are more issues.

**Comment by Sanokei** [comment]
@shaun-wild I wrote how to get it working on WSL here: https://github.com/MineDojo/MineDojo/issues/22#issuecomment-1200431684

**Comment by anonygituser** [comment]
I am using Ubuntu 22.04, but still doesn't working.
```
$ python scripts/validate_install.py
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
```
gets stuck after this. I kept it like this for 20-30 minutes multiple times.

I also tried running quick start code from minedojo.org, 
```
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
/home/asmit/.local/lib/python3.10/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
[INFO:minedojo.tasks] Loaded 1572 Programmatic tasks, 1558 Creative tasks, and 1 special task: "Playthrough". Totally 3131 tasks loaded.
```

How should I proceed.

**Comment by Sanokei** [comment]
> /home/asmit/.local/lib/python3.10/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32

your using python 3.10
download python 3.9
reinstall minedojo with pip for 3.9
run it with that
