### ISSUE TITLE
Failling to install in Ubuntu 20.04 and Arch linux

### ISSUE THREAD

**Issue by enriquead1** [MineDojo/MineDojo#27]
I am failing to correctly install the package in my system. There is no error when I run "pip install -e .", but the evaluation is not successful with "validate_install.py". 

The error that I receive is: "Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0."

Just in case, the version of arch linux that I am running is "5.18.9-arch1-1". The version of Ubuntu that I am using comes from the official docker image for python, where I installed default-jre, ffmpeg, libsm6, libxext6.

**Comment by yunfanjiang** [comment]
Hey @enriquead1 , thank you for trying out. Could you please attach a full stack of error so I can take a look?

**Comment by enriquead1** [comment]
Hello,
I am uploading the full output I get when running validate_install.py at sublime api
[stack error.txt](https://github.com/MineDojo/MineDojo/files/9280475/stack.error.txt)
.

**Comment by enriquead1** [comment]
Problem solved. I was using java 11 instead of java 8.
