### ISSUE TITLE
MineDojo Crashing

### ISSUE THREAD

**Issue by RocketNinja15** [MineDojo/MineDojo#28]
Hey! 

After running and it working once, now it crashes. 

https://hastebin.com/cukizamuxe.sql

**Comment by yunfanjiang** [comment]
Hey @RocketNinja15 , thanks for reporting this! Have you double-checked that the Java version is the same as the one you used to successfully run?

**Comment by yunfanjiang** [comment]
Closed since the issue seems resolved. Feel free to reopen if it sill exists.
