### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by stinkytoot200** [MineDojo/MineDojo#29]
I'm a complete noob so i don't really know what im doing, i just want to try this out!
After installing it, when i test if it installed correctly it says it cant find the file.
![image](https://user-images.githubusercontent.com/86577879/183330976-3e3f5f06-b27b-4f0f-b75b-1699ff13d146.png)

**Comment by stinkytoot200** [comment]
i've tried both conda and pip and they both had the same error

**Comment by enriquead1** [comment]
You are not pointing to the right directory. You have to run the validate_install.py, so look for the right path. Probably just changing minedojo for MineDojo is enough.

**Comment by stinkytoot200** [comment]
> You are not pointing to the right directory. You have to run the validate_install.py, so look for the right path. Probably just changing minedojo for MineDojo is enough.

i don't even think validate_Install exists, ive searched my whole computer and nothing came up

**Comment by stinkytoot200** [comment]
I've tried conda, pip, and docker, and nothing is working :(

**Comment by LinxiFan** [comment]
For windows installation, I recommend Sanokei's solution here: https://github.com/MineDojo/MineDojo/issues/22#issuecomment-1200431684. But please note that we do not train AI models on windows, so there is not much support there. Thanks for your interest!
