### ISSUE TITLE
Unable to build the environment

### ISSUE THREAD

**Issue by siriusctrl** [MineDojo/MineDojo#3]
Unable to build the env by following the instruction in readme, either install minedojo from pypi or in editable mode. It mentioned that

```
> Task :extractUserdev FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':forgeGradleUserDevPackage'.
> Could not download forge-userdev.jar (net.minecraftforge:forge:1.11.2-13.20.1.2588)
   > Could not get resource 'https://maven.minecraftforge.net/net/minecraftforge/forge/1.11.2-13.20.1.2588/forge-1.11.2-13.20.1.2588-userdev.jar'.
      > Premature end of Content-Length delimited message body (expected: 4680732; received: 4079288
```

Similar build problem can also be observed in Colab. Does anyone have an idea on this?

**Comment by yunfanjiang** [comment]
Hi @siriusctrl, thanks for reporting this! Could you please attach the full error message when you encounter again next time?

**Comment by siriusctrl** [comment]
Hi @yunfanjiang, I think you can refer to #4 for the full stack trace. One more thing is that, to be able to run the env on Linux, you need some extra dependency that does not mentioned in the doc, but only at the colab. They are
```
apt-get install xserver-xephyr vnc4server python-opengl ffmpeg
```

**Comment by yunfanjiang** [comment]
> 

Thank you for pointing me to the full log. Did you run in a headless Linux machine? If yes, did you prepend `xvfb-run` to use software renderer? Also it this a persistent failure?

**Comment by yunfanjiang** [comment]
> Hi @yunfanjiang, I think you can refer to #4 for the full stack trace. One more thing is that, to be able to run the env on Linux, you need some extra dependency that does not mentioned in the doc, but only at the colab. They are
> 
> ```
> apt-get install xserver-xephyr vnc4server python-opengl ffmpeg
> ```

Thank you for pointing me to the full log. Also appreciate mentioning missed dependencies. 
Regarding the launching error, is it a persistent issue?

**Comment by yunfanjiang** [comment]
Could you please also let me know your system info? See #4 it may not work on Ubuntu 16.04

**Comment by siriusctrl** [comment]
This is not a persistent issue but is only triggered randomly. We tested on Ubuntu 18.04 and 20.04 (container). Both can run most of the time. Unfortunately, we did not record the stack trace this time, but it related to the `run_client` problem mentioned in #4. 

One more thing is that, once the docker image was built (which I mean we successfully launch the env for a single time), we are unable to rerun the env if we rebuild the docker image elsewhere. There is no error message, but the env seems to get stuck somewhere for a day. So I was wounding, is there any plan for you guys to release the official docker image recently?

**Comment by yunfanjiang** [comment]
> This is not a persistent issue but is only triggered randomly. We tested on Ubuntu 18.04 and 20.04 (container). Both can run most of the time. Unfortunately, we did not record the stack trace this time, but it related to the `run_client` problem mentioned in #4.
> 
> One more thing is that, once the docker image was built (which I mean we successfully launch the env for a single time), we are unable to rerun the env if we rebuild the docker image elsewhere. There is no error message, but the env seems to get stuck somewhere for a day. So I was wounding, is there any plan for you guys to release the official docker image recently?

Thank you for letting me know. Yes, we indeed have a plan to release the self-contained docker image. Please stay tuned. Close this issue now.

**Comment by yunfanjiang** [comment]
Hey @siriusctrl , a follow-up on our release of the Docker image https://github.com/MineDojo/MineDojo/releases/tag/docker

**Comment by albertcity** [comment]
> Thanks for the advice. After trying various proxy, I can now successfully launch the env. However, there is a small probability that the env cannot connect to the client and report

I faced the same problem. I have tried to launch the env by using `proxychains`, however, this will lead to other problems. Can you tell me how you use a proxy to successfully launch the env? Thanks!
