### ISSUE TITLE
The number of target animals increases using env.reset()

### ISSUE THREAD

**Issue by YHQpkueecs** [MineDojo/MineDojo#33]
Hello, 
In harvest_milk and harvest_wool tasks, when calling reset(), the environment produces a new cow/sheep and keeps the old animals. To train an RL agent, it makes the task easier to solve when calling more reset(), because the animals are easier to find. 

figure: during training, the number of cows increases after many environment episodes.
![微信图片_20220819182831](https://user-images.githubusercontent.com/38282119/185599830-b1f873c7-4e3c-4d27-9856-4ed86b068886.jpg)
My environment is made with env = minedojo.make(task_id='harvest_milk_with_empty_bucket_and_cow', image_size=(256,256))

Could you check for this issue?

**Comment by yunfanjiang** [comment]
Hey, thanks for reporting this. Please refer to [this](https://github.com/MineDojo/MineCLIP/blob/5ec098c1660da44933ae9a221ea3ee180f973e0d/mineclip/dense_reward/animal_zoo/hunt_cow.py#L62) to eliminate spawned mobs during reset. At this point users need to call this manually. We will integrate it at some point. Sorry for the inconvenience.
