### ISSUE TITLE
Does the task in the folder generate templates

### ISSUE THREAD

**Issue by yifan123** [MineDojo/MineDojo#38]
Hi,
Thanks for this amazing work and releasing the code! I have some questions.

1. Is the tasks in the file (https://github.com/MineDojo/MineDojo/blob/main/minedojo/tasks/description_files/tasks_suite.yaml) the meta templates? That is to say, we use 32 templates to generate a number of variations based on the terrain, initial inventory, quantity, etc. for the programmatic_tasks.

2. What's the meaning of 'creative_tasks' in tasks_suite.yaml? The paper mentioned that the authors exported more than 1,000 creative tasks from YouTube videos, which were not template generated.

Thanks~

**Comment by yunfanjiang** [comment]
Thank you for your interest in our work. To answer your questions
1. Yes, those are "meta" templates that can be procedurally instantiated into a bunch of tasks with different variations.
2. Those are for creative tasks. Though we didn't generate them from templates, we do store relevant filed such as prompts and instructions in that file.
