### ISSUE TITLE
Execution failed for task ':runClient'. on linux

### ISSUE THREAD

**Issue by WannianXia** [MineDojo/MineDojo#4]
When I tried to verify the installation of MineDojo with ```xvfb-run python validate_install.py``` in a linux server, I got a Minecraft Crash Report says:
![Screen Shot 2022-06-29 at 19 22 35](https://user-images.githubusercontent.com/105784508/176425135-5109e2c0-dd86-4947-a431-42f60415d587.png)

And it seems to do something with the ```runClient``` task:
![Screen Shot 2022-06-29 at 19 23 41](https://user-images.githubusercontent.com/105784508/176425334-ec940e08-c0f4-48d2-84c6-73a850fd4612.png)

Any help would be appreciated.

**Comment by yunfanjiang** [comment]
Thanks for reporting this issue! Could you please attach the full stack of error messages and I'd like to take a look

**Comment by WannianXia** [comment]
> Thanks for reporting this issue! Could you please attach the full stack of error messages and I'd like to take a look

Thanks a lot! Here is the full log.

[validate_install.log](https://github.com/MineDojo/MineDojo/files/9015617/validate_install.log)

**Comment by yunfanjiang** [comment]
> > Thanks for reporting this issue! Could you please attach the full stack of error messages and I'd like to take a look
> 
> Thanks a lot! Here is the full log.
> 
> [validate_install.log](https://github.com/MineDojo/MineDojo/files/9015617/validate_install.log)

Thank you for attaching the full log. Is this a persistent issue?

**Comment by WannianXia** [comment]
> > > Thanks for reporting this issue! Could you please attach the full stack of error messages and I'd like to take a look
> > 
> > 
> > Thanks a lot! Here is the full log.
> > [validate_install.log](https://github.com/MineDojo/MineDojo/files/9015617/validate_install.log)
> 
> Thank you for attaching the full log. Is this a persistent issue?

It seems to be the problem with the system version. This issue was found on Ubuntu 16.04.
I've tried installing and testing MineDojo on another Linux server running Ubuntu 18.04, and it just worked.
Thank you for your concern. You may close this issue if you don't intend to support MineDojo on older systems.

**Comment by yunfanjiang** [comment]
> > > > Thanks for reporting this issue! Could you please attach the full stack of error messages and I'd like to take a look
> > > 
> > > 
> > > Thanks a lot! Here is the full log.
> > > [validate_install.log](https://github.com/MineDojo/MineDojo/files/9015617/validate_install.log)
> > 
> > 
> > Thank you for attaching the full log. Is this a persistent issue?
> 
> It seems to be the problem with the system version. This issue was found on Ubuntu 16.04. I've tried installing and testing MineDojo on another Linux server running Ubuntu 18.04, and it just worked. Thank you for your concern. You may close this issue if you don't intend to support MineDojo on older systems.

Thank you for the information! We tested MineDojo on Ubuntu 20.04 and MacOS intel chip prior to release. It may or may not work on other platform. Good to know it can work on Ubuntu 18.04. We will update the doc accordingly.
