### ISSUE TITLE
python: can't open file '/home/daniel/minedojo/scripts/validate_install.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jafwefjauwhf** [MineDojo/MineDojo#43]
When I try to use the windows 10 instructions, this pops up when doing the validating. Help?
![image](https://user-images.githubusercontent.com/69084337/195439890-2a73dad9-2eae-4f55-8122-c328dab4deef.png)

**Comment by subelsky** [comment]
have you double-checked that `/home/daniel/minedojo` exists? when you clone `MineDojo/MineDojo` you're creating the `MineDojo` directory, not `minedojo` which the directions specify. this tripped me up for a sec as well

**Comment by Gnomecromancer** [comment]
I am having the same issue and this fix returns the same error message as before.
