### ISSUE TITLE
How to deal with the permission issue for '/tmp'

### ISSUE THREAD

**Issue by hzwer** [MineDojo/MineDojo#49]
![image](https://user-images.githubusercontent.com/10103856/208088092-c197da97-96da-43c9-8f33-c65c3806cffb.png)

**Comment by hzwer** [comment]
I run this repo in the docker and everything goes well.

**Comment by a1wj1** [comment]
Have you solved it? I have the same problem

**Comment by Cu2ta1n** [comment]
same problem
