### ISSUE TITLE
Training time?

### ISSUE THREAD

**Issue by thesofakillers** [MineDojo/MineDojo#64]
Hi, I see from section D.3 in the appendix that your provide details on the hardware and setup for training. Could you comment on how long in real time training took with this setup?

Thanks!

**Comment by thesofakillers** [comment]
Hi @yunfanjiang -- any comment on this? Rough estimates are completely fine. Thanks!

**Comment by yunfanjiang** [comment]
Hey @thesofakillers, for almost all experiments we ran for 2M to 4M environment steps, which took roughly 1 day and 2 days on our machines.

**Comment by thesofakillers** [comment]
Thanks!
