### ISSUE TITLE
How to save videos?

### ISSUE THREAD

**Issue by rdejana** [MineDojo/MineDojo#7]
Is it possible so save a video?  If so, how?

**Comment by yunfanjiang** [comment]
Hey @rdejana , it's possible to save videos by using common third-party utils. What we need to do is just collect RGB from obs. The code snippet below demonstrates how to do this using `torchvision`.

```
# some setup
rgb_list = []

for _ in range(num_steps_you_want_to_run):
    # get actions
    obs, reward, done, info = env.step(action)
    rgb_list.append(obs["rgb"])
rgbs = np.stack(rgb_list)
rgbs = torch.from_numpy(rgbs)
torchvision.io.write_video(save_path, rgbs, fps=fps)
```

Let me know if you have any further questions!

**Comment by rdejana** [comment]
thank you!

**Comment by rdejana** [comment]
For anybody else, with the latest PyTorch / Torchvision, I needed to add the following to reorder tensor.
```
rgbs = rgbs.permute(0,2,3,1)
```

**Comment by Cu2ta1n** [comment]
Is there a method similar to a gym monitor?
