### ISSUE TITLE
MineCLIP and RL Agents

### ISSUE THREAD

**Issue by rajammanabrolu** [MineDojo/MineDojo#9]
Hi, in order to compare other agents we have developed to the one in the paper with reproducibility, we'd need access to the trained MineCLIP and code to load it, etc. in addition to the code for baseline PPO+Self Imitation Agent. Could you please release these components?

**Comment by LinxiFan** [comment]
Hi Prithviraj, thanks for your interest! I replied to you over email.

**Comment by chenllliang** [comment]
Hi, can I have a copy of the  baseline PPO+Self Imitation Agent training code given the MineCLIP model? I am really interested in this work and hope to make progress based on the baseline model.

**Comment by AsWali** [comment]
@rajammanabrolu Did you get the code for the PPO + SI ? If so, would it be possible for you to share those with me ?
