### ISSUE TITLE
Is it possible for a human player to interact with an agent in Minecraft?

### ISSUE THREAD

**Issue by lincolnschick** [MineDojo/MineDojo#99]
I wasn't able to find any code for this in the repo or mention of it in the docs, so I assume this is not currently possible, but I wanted to make sure I haven't missed anything as this is a requirement for my use case.

If it is not currently implemented, is there a particular reason? I would think it would be since I saw MineRL v0.4 has an [interactor](https://github.com/minerllabs/minerl/blob/40a9e35c086c4dc7959ad473ec765cd4828c4631/minerl/interactor/__main__.py#L46) component. If there were no technical barriers to it, I may implement it myself.

Thanks!

**Comment by Bpoole908** [comment]
Did you ever achieve this?

**Comment by lincolnschick** [comment]
No, I didn't look into it anymore. MineRL v0.4 met my needs, so I never used MineDojo
